CREATE TABLE investors(
investor_id serial primary key,
investor_name varchar(30) not null,
investor_type varchar(30) not null,
hq_country varchar(30) not null
);

insert into investors (investor_name,investor_type,hq_country)
values
('Sequoia Capital', 'Venture Capital', 'USA'),
('Accel Partners', 'Venture Capital', 'USA'),
('Tiger Global', 'Venture Capital', 'USA'),
('SoftBank Vision Fund', 'Venture Capital', 'Japan'),
('Andreessen Horowitz', 'Venture Capital', 'USA'),
('Lightspeed Venture Partners', 'Venture Capital', 'USA'),
('Y Combinator', 'Accelerator', 'USA'),
('500 Startups', 'Accelerator', 'USA'),
('General Catalyst', 'Venture Capital', 'USA'),
('Matrix Partners', 'Venture Capital', 'USA'),
('Blume Ventures', 'Venture Capital', 'India'),
('Nexus Venture Partners', 'Venture Capital', 'India'),
('Sequoia India', 'Venture Capital', 'India'),
('IDG Ventures', 'Venture Capital', 'India'),
('Khosla Ventures', 'Venture Capital', 'USA'),
('GV (Google Ventures)', 'Corporate VC', 'USA'),
('Intel Capital', 'Corporate VC', 'USA'),
('Samsung NEXT', 'Corporate VC', 'South Korea'),
('Temasek Holdings', 'Private Equity', 'Singapore'),
('SoftBank Group', 'Corporate Investor', 'Japan'),
('Tiger Global India', 'Venture Capital', 'India'),
('Lightspeed India', 'Venture Capital', 'India'),
('Emergence Capital', 'Venture Capital', 'USA'),
('Bessemer Venture Partners', 'Venture Capital', 'USA'),
('Falcon Edge Capital', 'Private Equity', 'USA'),
('GVF (Global Ventures Fund)', 'Venture Capital', 'UK'),
('Accel India', 'Venture Capital', 'India'),
('Alpha JWC Ventures', 'Venture Capital', 'Indonesia'),
('East Ventures', 'Venture Capital', 'Indonesia'),
('Golden Gate Ventures', 'Venture Capital', 'Singapore'),
('Venturra Capital', 'Venture Capital', 'Indonesia'),
('Digital Garage', 'Corporate VC', 'Japan'),
('Fireside Ventures', 'Venture Capital', 'India'),
('Inventus Capital Partners', 'Venture Capital', 'India'),
('Vertex Ventures', 'Venture Capital', 'Singapore'),
('ChrysCapital', 'Private Equity', 'India'),
('IDFC Private Equity', 'Private Equity', 'India'),
('Ratan Tata', 'Angel Investor', 'India'),
('Naveen Jain', 'Angel Investor', 'USA');