CREATE TABLE startups(
startup_id serial primary key,
startup_name varchar(40) not null unique,
industry varchar(30) not null,
founded_year int not null,
city varchar(30) not null,
country varchar(30) not null
);

insert into startups(startup_name,industry,founded_year,city,country)
values
('TechNova', 'Technology', 2015, 'Bangalore', 'India'),
('GreenLeaf', 'Agriculture', 2018, 'San Francisco', 'USA'),
('HealthPlus', 'Healthcare', 2017, 'London', 'UK'),
('EduSpark', 'Education', 2016, 'Berlin', 'Germany'),
('FinWise', 'Finance', 2019, 'New York', 'USA'),
('AutoMinds', 'Automobile', 2020, 'Munich', 'Germany'),
('FoodieHub', 'Food & Beverages', 2018, 'Paris', 'France'),
('EcoBuild', 'Construction', 2014, 'Toronto', 'Canada'),
('TravelEase', 'Tourism', 2021, 'Singapore', 'Singapore'),
('MediTrack', 'Healthcare', 2019, 'Mumbai', 'India'),
('CodeCraft', 'Technology', 2013, 'San Jose', 'USA'),
('FarmConnect', 'Agriculture', 2020, 'Nairobi', 'Kenya'),
('LearnLoop', 'Education', 2017, 'Sydney', 'Australia'),
('FinEdge', 'Finance', 2016, 'Chicago', 'USA'),
('AutoDrive', 'Automobile', 2018, 'Detroit', 'USA'),
('TasteBuds', 'Food & Beverages', 2021, 'Rome', 'Italy'),
('GreenConstruct', 'Construction', 2015, 'Amsterdam', 'Netherlands'),
('TripMate', 'Tourism', 2019, 'Bangkok', 'Thailand'),
('MediCare', 'Healthcare', 2016, 'Delhi', 'India'),
('SoftSolutions', 'Technology', 2014, 'Toronto', 'Canada'),
('AgroTech', 'Agriculture', 2019, 'Hyderabad', 'India'),
('SmartLearn', 'Education', 2020, 'Dublin', 'Ireland'),
('WealthWise', 'Finance', 2018, 'London', 'UK'),
('AutoSense', 'Automobile', 2017, 'Tokyo', 'Japan'),
('GourmetGo', 'Food & Beverages', 2015, 'Barcelona', 'Spain'),
('BuildSmart', 'Construction', 2021, 'Melbourne', 'Australia'),
('Wanderlust', 'Tourism', 2014, 'Cape Town', 'South Africa'),
('HealthSync', 'Healthcare', 2020, 'Boston', 'USA'),
('TechSphere', 'Technology', 2016, 'Seoul', 'South Korea'),
('CropConnect', 'Agriculture', 2015, 'Buenos Aires', 'Argentina'),
('Learnify', 'Education', 2018, 'Zurich', 'Switzerland'),
('FinMaster', 'Finance', 2017, 'Singapore', 'Singapore'),
('DriveSmart', 'Automobile', 2019, 'Shanghai', 'China'),
('FoodChain', 'Food & Beverages', 2020, 'Lisbon', 'Portugal'),
('UrbanBuild', 'Construction', 2016, 'Vienna', 'Austria'),
('Tourista', 'Tourism', 2018, 'Istanbul', 'Turkey'),
('MediLink', 'Healthcare', 2014, 'Kuala Lumpur', 'Malaysia'),
('ByteWorks', 'Technology', 2021, 'Bangalore', 'India'),
('AgriConnect', 'Agriculture', 2017, 'Lagos', 'Nigeria'),
('EduVerse', 'Education', 2019, 'New York', 'USA'),
('FinFlow', 'Finance', 2020, 'Toronto', 'Canada'),
('AutoPilot', 'Automobile', 2015, 'Detroit', 'USA'),
('SnackHub', 'Food & Beverages', 2016, 'Paris', 'France'),
('ConstructIt', 'Construction', 2017, 'Berlin', 'Germany'),
('TravelNext', 'Tourism', 2021, 'Singapore', 'Singapore'),
('HealthWave', 'Healthcare', 2018, 'Mumbai', 'India'),
('CodeHive', 'Technology', 2014, 'London', 'UK'),
('FarmLink', 'Agriculture', 2021, 'Nairobi', 'Kenya'),
('LearnSmart', 'Education', 2015, 'Sydney', 'Australia'),
('FinTechPro', 'Finance', 2019, 'San Francisco', 'USA'),
('DriveHub', 'Automobile', 2020, 'Tokyo', 'Japan'),
('GustoBite', 'Food & Beverages', 2017, 'Rome', 'Italy'),
('BuildWise', 'Construction', 2018, 'Amsterdam', 'Netherlands'),
('TripGuide', 'Tourism', 2016, 'Bangkok', 'Thailand'),
('MediCarePlus', 'Healthcare', 2015, 'Delhi', 'India'),
('TechFusion', 'Technology', 2019, 'Seoul', 'South Korea'),
('AgriNext', 'Agriculture', 2016, 'Hyderabad', 'India'),
('SmartEdu', 'Education', 2020, 'Dublin', 'Ireland'),
('WealthPro', 'Finance', 2014, 'London', 'UK'),
('AutoTech', 'Automobile', 2018, 'Detroit', 'USA'),
('FoodFest', 'Food & Beverages', 2021, 'Barcelona', 'Spain'),
('EcoConstruct', 'Construction', 2017, 'Melbourne', 'Australia'),
('TravelPro', 'Tourism', 2015, 'Cape Town', 'South Africa');
